name = "lotus-compat"

[defaults]
builder = "docker:generic"
runner = "cluster:k8s"

[builders."docker:generic"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "default"
instances = { min = 1, max = 1, default = 1 }
